//
//  TableWireframe.swift
//  Coinmarketcap Test
//
//  Created by Roman Slysh on 9/5/18.
//  Copyright (c) 2018 Roman. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class TableWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard = UIStoryboard(name: "Table", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = _storyboard.instantiateViewController(ofType: TableViewController.self)
        super.init(viewController: moduleViewController)

        let interactor = TableInteractor()
        let presenter = TablePresenter(wireframe: self, view: moduleViewController, interactor: interactor)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension TableWireframe: TableWireframeInterface {

    func navigate(to option: TableNavigationOption) {
    }
}
