//
//  TableInteractor.swift
//  Coinmarketcap Test
//
//  Created by Roman Slysh on 9/5/18.
//  Copyright (c) 2018 Roman. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class TableInteractor {
}

// MARK: - Extensions -

extension TableInteractor: TableInteractorInterface {
}
